//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyperVProxyManager.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class l10n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal l10n() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HyperVProxyManager.Resources.l10n", typeof(l10n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 System proxy disabled 的本地化字符串。
        /// </summary>
        public static string CurrentProxyDisabled {
            get {
                return ResourceManager.GetString("CurrentProxyDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Enabled 的本地化字符串。
        /// </summary>
        public static string CurrentProxyNotEnable {
            get {
                return ResourceManager.GetString("CurrentProxyNotEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable 的本地化字符串。
        /// </summary>
        public static string DashButtonDisable {
            get {
                return ResourceManager.GetString("DashButtonDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply Host IP 的本地化字符串。
        /// </summary>
        public static string DashButtonQuickSet {
            get {
                return ResourceManager.GetString("DashButtonQuickSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string DashButtonRefresh {
            get {
                return ResourceManager.GetString("DashButtonRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Host IPv4 的本地化字符串。
        /// </summary>
        public static string DashCardHost {
            get {
                return ResourceManager.GetString("DashCardHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current System Proxy 的本地化字符串。
        /// </summary>
        public static string DashCardProxy {
            get {
                return ResourceManager.GetString("DashCardProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detecting... 的本地化字符串。
        /// </summary>
        public static string HostIpAddressDetecting {
            get {
                return ResourceManager.GetString("HostIpAddressDetecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VM gateway not detected 的本地化字符串。
        /// </summary>
        public static string HostIpAddressNotDetected {
            get {
                return ResourceManager.GetString("HostIpAddressNotDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not set 的本地化字符串。
        /// </summary>
        public static string ProxyNotSet {
            get {
                return ResourceManager.GetString("ProxyNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Warning] Operation completely failed. Settings update error code: {0}, Proxy refresh error code: {1} 的本地化字符串。
        /// </summary>
        public static string ResultErrBoth {
            get {
                return ResourceManager.GetString("ResultErrBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to open or create registry key 的本地化字符串。
        /// </summary>
        public static string ResultErrOpenRegisty {
            get {
                return ResourceManager.GetString("ResultErrOpenRegisty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Warning] Failed to refresh proxy settings. Error code: {0} 的本地化字符串。
        /// </summary>
        public static string ResultErrRefresh {
            get {
                return ResourceManager.GetString("ResultErrRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Error] Security exception, unable to access the registry. 的本地化字符串。
        /// </summary>
        public static string ResultErrSecurity {
            get {
                return ResourceManager.GetString("ResultErrSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Warning] Failed to notify system setting changes. Error code: {0} 的本地化字符串。
        /// </summary>
        public static string ResultErrSettingChanged {
            get {
                return ResourceManager.GetString("ResultErrSettingChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Error] Insufficient permissions, unable to write to the registry. 的本地化字符串。
        /// </summary>
        public static string ResultErrUnauthorized {
            get {
                return ResourceManager.GetString("ResultErrUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Error] Unexpected exception: {0} 的本地化字符串。
        /// </summary>
        public static string ResultErrUnexpected {
            get {
                return ResourceManager.GetString("ResultErrUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation complete: System proxy disabled 的本地化字符串。
        /// </summary>
        public static string ResultSccDisable {
            get {
                return ResourceManager.GetString("ResultSccDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation complete: Proxy set to {0} 的本地化字符串。
        /// </summary>
        public static string ResultSccEnable {
            get {
                return ResourceManager.GetString("ResultSccEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read proxy port configuration from external config.ini file. 的本地化字符串。
        /// </summary>
        public static string SettingsCustomDescription {
            get {
                return ResourceManager.GetString("SettingsCustomDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom Configuration 的本地化字符串。
        /// </summary>
        public static string SettingsCustomHeader {
            get {
                return ResourceManager.GetString("SettingsCustomHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specify the port the host proxy software listens on (1-65535). 的本地化字符串。
        /// </summary>
        public static string SettingsPortDescription {
            get {
                return ResourceManager.GetString("SettingsPortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy Port 的本地化字符串。
        /// </summary>
        public static string SettingsPortHeader {
            get {
                return ResourceManager.GetString("SettingsPortHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready 的本地化字符串。
        /// </summary>
        public static string StatusMessageDefault {
            get {
                return ResourceManager.GetString("StatusMessageDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh complete 的本地化字符串。
        /// </summary>
        public static string StatusMessageRefreshed {
            get {
                return ResourceManager.GetString("StatusMessageRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refreshing... 的本地化字符串。
        /// </summary>
        public static string StatusMessageRefreshing {
            get {
                return ResourceManager.GetString("StatusMessageRefreshing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable Proxy 的本地化字符串。
        /// </summary>
        public static string TrayDisableProxy {
            get {
                return ResourceManager.GetString("TrayDisableProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string TrayExit {
            get {
                return ResourceManager.GetString("TrayExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quick Apply 的本地化字符串。
        /// </summary>
        public static string TrayQuickSet {
            get {
                return ResourceManager.GetString("TrayQuickSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Main Window 的本地化字符串。
        /// </summary>
        public static string TrayShowMainWindow {
            get {
                return ResourceManager.GetString("TrayShowMainWindow", resourceCulture);
            }
        }
    }
}
